### ISSUE TITLE
dcraw returning non zero exit status

### ISSUE THREAD

**Issue by SamWhited** [photoshell/photoshell#103]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sam/Projects/photoshell/photoshell/views/photo_import.py", line 124, in do_import
    delete_originals=self.options['delete_originals'])
  File "/home/sam/Projects/photoshell/photoshell/library.py", line 101, in import_photos
    cache_path=self.cache_path,
  File "/home/sam/Projects/photoshell/photoshell/photo.py", line 113, in develop
    ['dcraw', '-c', '-e', self.raw_path])
  File "/usr/lib64/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['dcraw', '-c', '-e', '']' returned non-zero exit status 1
```

Can't reproduce by running dcraw against the photos manually; I wonder if it thinks it's outputting to a terminal for some reason? Or maybe `raw_path` is pointing somewhere weird (checking).

It would be nice if we didn't have to rely on dcraw at all. Maybe use rawphoto to extract thumbnails and just support CR2 for now? I'm sure we can find something in python to generate a tiff with so we don't have to be calling out to something external.

**Comment by SamWhited** [comment]
`self.raw_photo` is an empty string. Backing up to see why it's not being set now.

**Comment by SamWhited** [comment]
`dict_to_tuple(Photo, metadata)` in `photo.py` uses an existing sidecar which doesn't have `raw_path`.
