### ISSUE TITLE
Importing while copying files broken

### ISSUE THREAD

**Issue by SamWhited** [photoshell/photoshell#116]
After the last refactor, importing while copying files was broken.

No image path:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sam/Projects/photoshell/photoshell/views/photo_import.py", line 132, in do_import
    self._window.selection
  File "/home/sam/Projects/photoshell/photoshell/library.py", line 68, in update
    image_path = current.image_path
AttributeError: 'Photo' object has no attribute 'image_path'
```

And after updating the image path:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sam/Projects/photoshell/photoshell/views/photo_import.py", line 132, in do_import
    self._window.selection
  File "/home/sam/Projects/photoshell/photoshell/library.py", line 71, in update
    new_selection.jump(image_path)
AttributeError: 'Selection' object has no attribute 'jump'
```

**Comment by SamWhited** [comment]
This appears to have been fixed at some point.
