### ISSUE TITLE
'Photo' object has no attribute 'image_path'

### ISSUE THREAD

**Issue by campaul** [photoshell/photoshell#140]
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cameron/Workspace/photoshell/photoshell/views/photo_import.py", line 132, in do_import
    self._window.selection
  File "/home/cameron/Workspace/photoshell/photoshell/library.py", line 68, in update
    image_path = current.image_path
AttributeError: 'Photo' object has no attribute 'image_path'

**Comment by campaul** [comment]
This happens on import sometimes. Not sure why yet.
