### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by campaul** [photoshell/photoshell#81]
I get the following whenever I try to do an import:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cameron/Workspace/photoshell/photoshell/views/photo_import.py", line 122, in do_import
    delete_originals=self.options['delete_originals'])
  File "/home/cameron/Workspace/photoshell/photoshell/library.py", line 93, in import_photos
    value = i.ifd[0].get_value(i.ifd[0].find_entry(tag))
  File "/home/cameron/Workspace/photoshell/env/src/photoshell/rawphoto/cr2.py", line 114, in get_value
    tag_type = entry.tag_type
AttributeError: 'NoneType' object has no attribute 'tag_type'
```

**Comment by SamWhited** [comment]
Fixed in fb7290e8504a8f1e57d59a082008aad06d2222ae
